server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8001/
          predicates:
            - Path=/api/v1/customers/**
        - id: route2
          uri: http://localhost:8002/
          predicates:
            - Path=/api/v1/cart/**

