server:
  port: 8080

spring:
#   redis:
#     host: localhost
#     port: 6379
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8001/
          predicates:
            - Path=/api/v1/customers/**
        - id: route2
          uri: http://localhost:8002/
          predicates:
            - Path=/api/v1/cart/**
#           filters:
#             - name: RequestRateLimiter
#               args:
#                 redis-rate-limiter.replenishRate: 20
#                 redis-rate-limiter.burstCapacity: 40
#                 redis-rate-limiter.requestedTokens: 1

